# This is a basic workflow to help you get started with Actions

name: Tag Version

permissions:
  contents: write

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "v*" ]
    types: [closed]

jobs:

     
  # This workflow contains a single job that increments the latest `patch` version
  # on the merged branch

  increment-patch:
    if: github.event.pull_request.merged == true

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
           
      - name: semver-utils
        id: semver
        uses: flox/semver-increment@master
        with:
          # A version to process
          base-version: ${{ github.base_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag new releases
        run: | 

          echo ${{steps.semver.outputs.next-version}}
          
          git tag --force v${{steps.semver.outputs.next-version}}
          git tag --force v${{ steps.semver.outputs.next-version-major }}.${{ steps.semver.outputs.next-version-minor }}
          
          git push --force --tags origin
