# This is a basic workflow to help you get started with Actions

name: Sync

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      "production-url":
        description: The production repo to update (for SSH access add a PRODUCTION_DEPLOY_KEY secret)
        required: true
        default: git@github.com:flox/capacitor.git

jobs:
  # This workflow contains a single job that increments the latest `patch` version
  # on the merged branch

  sync:
    name: Synchronize changes to Production

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch remaining tags and commits on branch ${{ github.ref_name }}
        run: |
          git fetch --prune --unshallow --tags origin ${{ github.ref }}

      - name: Ensure deploy key is present
        run: |
          if [[ ! -z "${{ secrets.PRODUCTION_DEPLOY_KEY }}" ]]
          then 
            echo "Setting up deploy-key"
            echo "${{ secrets.PRODUCTION_DEPLOY_KEY }}" > ./key
            chmod 400 ./key
            echo "GIT_SSH_COMMAND=ssh -i ./key" >> $GITHUB_ENV
          else
            echo "::error title=Missing deployment key::Please add the PRODUCTION_DEPLOY_KEY secret to contain your private deploy key"
            exit 1
          fi

      - name: Add production remote
        run: |
          git remote add production ${{ inputs.production-url }}

      - name: Push to production remote
        run: |
          git push --force --tags production ${{ github.ref }}
